spring:
  data:
    mongodb:
      authentication-database: admin
      host: 192.168.0.18
      password: admin
      username: admin
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      database: books
      port: 27017
    elasticsearch:
      repositories:
        enabled: false
  redis:
    database: 2
    port: 22334
    host: 192.168.0.13
    lettuce:
      pool:
        max-active: 2
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: Phoebus
  session:
    store-type: redis
    timeout: 90m
session-redis-db: 1